"""
CreateTestPR
============
Writes generated test files to disk and (unless ``dry_run`` is set) commits
them on a new git branch and opens a GitHub pull request.

Inputs
------
generated_tests : list[dict]
    Output from GenerateUnitTests.
repo_path : str, optional
    Local repo root.  Defaults to ``"."``.
github_api_key : str, optional
    GitHub personal access token.  Required unless ``dry_run=True``.
base_branch : str, optional
    PR target branch.  Defaults to ``"main"``.
pr_branch_prefix : str, optional
    New branch name prefix.  Defaults to ``"nullshift/auto-tests"``.
dry_run : bool, optional
    When ``True`` write files locally but skip git and GitHub operations.

Outputs
-------
pr_url : str
    URL of the created PR, or ``"dry_run"`` when skipping GitHub.
written_files : list[str]
    Paths of test files written to disk.
"""
from __future__ import annotations

import textwrap
import uuid
from pathlib import Path
from typing import List

from typing_extensions import TypedDict

from patchwork.logger import logger
from patchwork.step import Step

# ---------------------------------------------------------------------------
# TypedDicts
# ---------------------------------------------------------------------------


class _Inputs(TypedDict, total=False):
    repo_path: str
    github_api_key: str
    base_branch: str
    pr_branch_prefix: str
    dry_run: bool


class _Required(TypedDict):
    generated_tests: List[dict]


class Inputs(_Required, _Inputs):
    pass


class Outputs(TypedDict):
    pr_url: str
    written_files: List[str]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _write_test_files(generated_tests: list[dict], repo_path: Path) -> dict[str, str]:
    """Write test source to disk.  Returns {test_file: source} map (deduped by file)."""
    file_map: dict[str, str] = {}
    for entry in generated_tests:
        test_path = entry["test_file"]
        # Merge multiple functions into the same file (last write wins if already combined by GenerateUnitTests)
        if test_path not in file_map:
            file_map[test_path] = entry["test_source"]

    written: dict[str, str] = {}
    for rel_path, source in file_map.items():
        abs_path = repo_path / rel_path
        abs_path.parent.mkdir(parents=True, exist_ok=True)
        abs_path.write_text(source, encoding="utf-8")
        written[rel_path] = source
        logger.info(f"  Written: {abs_path}")
    return written


def _git_commit_and_push(repo_path: Path, branch: str, files: list[str], base_branch: str) -> None:
    """Create branch, stage files, commit, and push."""
    import git  # gitpython

    repo = git.Repo(repo_path)
    # Create and checkout new branch from current HEAD
    new_branch = repo.create_head(branch)
    new_branch.checkout()

    repo.index.add([str(repo_path / f) for f in files])
    repo.index.commit(
        textwrap.dedent(
            f"""\
            chore(nullshift): auto-generate unit tests

            Generated by NullShift for {len(files)} test file(s).
            Target branch: {base_branch}
            """
        )
    )
    origin = repo.remote("origin")
    origin.push(refspec=f"{branch}:{branch}")
    logger.info(f"Pushed branch '{branch}' to origin.")


def _open_github_pr(repo_path: Path, github_api_key: str, branch: str, base_branch: str, file_count: int) -> str:
    """Open a GitHub PR and return its HTML URL."""
    from github import Github  # PyGithub
    import git

    repo = git.Repo(repo_path)
    remote_url = repo.remote("origin").url  # e.g. git@github.com:org/repo.git

    # Parse org/repo from various URL formats
    import re
    match = re.search(r"[:/]([^/:]+/[^/]+?)(?:\.git)?$", remote_url)
    if not match:
        raise ValueError(f"Cannot parse GitHub org/repo from remote URL: {remote_url}")
    full_repo_name = match.group(1)

    gh = Github(github_api_key)
    gh_repo = gh.get_repo(full_repo_name)
    pr = gh_repo.create_pull(
        title=f"[NullShift] Auto-generated unit tests ({file_count} file(s))",
        body=textwrap.dedent(
            """\
            ## 🤖 NullShift — Auto-generated Tests

            This PR was created automatically by **NullShift**.  
            It adds pytest unit tests for functions detected on the PR diff that
            had no existing coverage.

            > Please review, adjust, and merge when satisfied.
            """
        ),
        head=branch,
        base=base_branch,
    )
    logger.info(f"GitHub PR created: {pr.html_url}")
    return pr.html_url


# ---------------------------------------------------------------------------
# Step
# ---------------------------------------------------------------------------


class CreateTestPR(Step, input_class=Inputs, output_class=Outputs):
    """Write generated tests to disk and optionally open a GitHub PR."""

    def __init__(self, inputs: dict):
        super().__init__(inputs)
        self._tests: list[dict] = inputs["generated_tests"]
        self._repo_path = Path(inputs.get("repo_path", ".")).resolve()
        self._github_api_key: str = inputs.get("github_api_key", "")
        self._base_branch: str = inputs.get("base_branch", "main")
        self._branch_prefix: str = inputs.get("pr_branch_prefix", "nullshift/auto-tests")
        self._dry_run: bool = bool(inputs.get("dry_run", False))

    def run(self) -> dict:
        if not self._tests:
            logger.info("CreateTestPR: nothing to commit.")
            return {"pr_url": "", "written_files": []}

        written = _write_test_files(self._tests, self._repo_path)
        written_files = list(written.keys())

        if self._dry_run:
            logger.info(f"CreateTestPR: dry_run=True — skipping git & GitHub. {len(written_files)} file(s) written.")
            return {"pr_url": "dry_run", "written_files": written_files}

        if not self._github_api_key:
            raise ValueError("github_api_key is required unless dry_run=True")

        branch = f"{self._branch_prefix}-{uuid.uuid4().hex[:8]}"
        logger.info(f"CreateTestPR: committing to branch '{branch}' …")

        _git_commit_and_push(self._repo_path, branch, written_files, self._base_branch)
        pr_url = _open_github_pr(
            self._repo_path,
            self._github_api_key,
            branch,
            self._base_branch,
            len(written_files),
        )

        return {"pr_url": pr_url, "written_files": written_files}
